"""
Repository interface definitions for persistence adapters.
"""
from __future__ import annotations

from typing import Iterable, Protocol

from mcp_server.domain import models


class PromptRepository(Protocol):
    def list(self) -> Iterable[models.Prompt]: ...

    def get(self, prompt_id: str) -> models.Prompt | None: ...

    def create(self, data: models.PromptCreate) -> models.Prompt: ...

    def update(self, prompt_id: str, data: models.PromptUpdate) -> models.Prompt | None: ...

    def delete(self, prompt_id: str) -> bool: ...


class ResourceRepository(Protocol):
    def list(self) -> Iterable[models.Resource]: ...

    def get(self, resource_id: str) -> models.Resource | None: ...

    def create(self, data: models.ResourceCreate) -> models.Resource: ...

    def update(self, resource_id: str, data: models.ResourceUpdate) -> models.Resource | None: ...

    def delete(self, resource_id: str) -> bool: ...


class ToolRepository(Protocol):
    def list(self) -> Iterable[models.Tool]: ...

    def get(self, tool_id: str) -> models.Tool | None: ...

    def create(self, data: models.ToolCreate) -> models.Tool: ...

    def update(self, tool_id: str, data: models.ToolUpdate) -> models.Tool | None: ...

    def delete(self, tool_id: str) -> bool: ...


